<?php

function custom_home_theme($existing, $type, $theme, $path) {
  return [
    'home_page' => [
      'variables' => [
        'contact_text' => NULL,
        'contact_form' => NULL,
      ],
    ],

    // @todo : rename to home_branding.
    'home_branding' => [
      'variables' => [
        'main_title' => NULL,
        'subtitle' => NULL,
        'cta' => NULL,
        'background_image' => NULL,
      ],
    ],

  ];
}
